name: 👷 Build, 🩺 Tests and 🛀 Lint

on:
  push:
    branches-ignore:
      - main
      - releases/**

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.0

  build:
    uses: ./.github/workflows/callable-build.yml
    needs: [cancel]
