name: 🧑‍🚀 Deploy projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - releases/**
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.0

  build:
    name: Build
    uses: ./.github/workflows/callable-build.yml
    needs: [cancel]

  deploy:
    name: Deploy
    uses: ./.github/workflows/callable-deployment.yml
    needs: [cancel, build]
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
